In [2]:
import numpy as np


<h1>Array Math</h1>

<h2>Task 1: Add, subtract, multiply and divide numpy arrays</h2>
Given the following Numpy arrays, answer the questions from (a) to (g) below.

a = np.arange(100,200,1).reshape(20,5)

b = np.arange(1,2000,20).reshape(10,10)

c = np.array([ [1,2,3], [4,5,6]])

(a) What happens when you try to perform the following operations on array a and array b?

print(a+b)

Answer: It returns an error as the array shape is not the same.

(b) Create an array a2 that has the same shape as array a, containing random numbers between
0 and 100. Print the contents of the resulting array when a and a2 are added together.

(c) Extract a subset of array b into an array variable b1, such that you can perform a subtraction
operation of (b1 – c) successfully. Print out the resulting contents of the array of this
operation.

(d) Create an array c2 such that c2 contains the values of array c multiplied by 10.


In [9]:
a = np.arange(100,200,1).reshape(20,5)
b = np.arange(1,2000,20).reshape(10,10)
c = np.array([[1,2,3],[4,5,6]])
a2 = np.arange(100,200,1).reshape(20,5)
b1 = b[:2,:3]
print(b1 - c)
c2 = c * 10
print(c2)
# print(a+a2)


[[  0  19  38]
 [197 216 235]]
[[10 20 30]
 [40 50 60]]


<h1>Statistical methods</h1>

<h2>Task 1: sum, mean</h2>

a = np.array((np.arange(0,10),
np.arange(10,20),
np.arange(20,30),
np.arange(30,40)))

(a) What is the sum of all the numbers in array a?

(b) What is their mean?

(c) What is the sum of all the numbers in each row?

Using the Numpy statistical functions sum() and mean(), compute the information for array a as
specified above

In [21]:
a = np.array((np.arange(0,10),
np.arange(10,20),
np.arange(20,30),
np.arange(30,40)))
print('Contents of array a')
print(a)
print('***Sum of all numbers in a***')
print(a.sum())
print('***Mean of all numbers in a***')
print(np.mean(a))
print('***Sum of all numbers in each row***')

for i in range(len(a)):
    print(f'Row {(i+1)} sum = {(np.sum(a[i]))}')

Contents of array a
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]
***Sum of all numbers in a***
780
***Mean of all numbers in a***
19.5
***Sum of all numbers in each row***
Row 1 sum = 45
Row 2 sum = 145
Row 3 sum = 245
Row 4 sum = 345


<h2>Task 2: std,var </h2>
a = np.arange(10,50,0.5)

b = np.arange(10,20,0.1)

(a) What is the standard deviation of arrays a and b?

(b) What is the variance of arrays a and b?

Using the Numpy statistical functions std() and var(), compute the information for array a as
specified. Your output should resemble the screenshot shown below

In [31]:
a = np.arange(10,50,0.5)

b = np.arange(10,20,0.1)

a_std = np.std(a)
b_std = np.std(b)
a_var = np.var(a)
b_var = np.var(b)
print('Contents of array a')
print(a)
print('Contents of array b')
print(b)
print('*** Standard Deviation ***')
print(f"SD of a : {a_std}")
print(f"SD of b : {b_std}")
print('*** Variance ***')
print(f"VAR of a : {a_var}")
print(f"VAR of b : {b_var}")

Contents of array a
[10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5 20.  20.5 21.  21.5 22.  22.5 23.  23.5
 24.  24.5 25.  25.5 26.  26.5 27.  27.5 28.  28.5 29.  29.5 30.  30.5
 31.  31.5 32.  32.5 33.  33.5 34.  34.5 35.  35.5 36.  36.5 37.  37.5
 38.  38.5 39.  39.5 40.  40.5 41.  41.5 42.  42.5 43.  43.5 44.  44.5
 45.  45.5 46.  46.5 47.  47.5 48.  48.5 49.  49.5]
Contents of array b
[10.  10.1 10.2 10.3 10.4 10.5 10.6 10.7 10.8 10.9 11.  11.1 11.2 11.3
 11.4 11.5 11.6 11.7 11.8 11.9 12.  12.1 12.2 12.3 12.4 12.5 12.6 12.7
 12.8 12.9 13.  13.1 13.2 13.3 13.4 13.5 13.6 13.7 13.8 13.9 14.  14.1
 14.2 14.3 14.4 14.5 14.6 14.7 14.8 14.9 15.  15.1 15.2 15.3 15.4 15.5
 15.6 15.7 15.8 15.9 16.  16.1 16.2 16.3 16.4 16.5 16.6 16.7 16.8 16.9
 17.  17.1 17.2 17.3 17.4 17.5 17.6 17.7 17.8 17.9 18.  18.1 18.2 18.3
 18.4 18.5 18.6 18.7 18.8 18.9 19.  19.1 19.2 19.3 19.4 19.5 19.6 19.7
 19.8 19.9]
*** Standard Deviation ***
SD of a : 11.5461

<h2>Task 3: min/ max, argmin/ argmax</h2>

a = np.random.randint(1,1000,(3,4))

Print out the following information:

maximum value of each row in array a

maximum value of the entire array a

row and column that has the number with the maximum value in array a

minimum value of each column in array a

minimum value of the entire array a

row and column that has the number with the minimum value in array a



In [64]:
a = np.random.randint(1,1000,(3,4))
print("***Contents of array a***")
print(a)
print(f"Max a = {(np.max(a))}")
max_loc = np.argmax(a,axis=1)
print(f'Row and Column is ([{max_loc[0]}],[{max_loc[1]}])')
print(f'Min a = {(np.min(a))}')
min_loc = np.argmin(a, axis=1)
print(f"Row and Column is ([{min_loc[0]}],[{min_loc[1]}])")

***Contents of array a***
[[283 280 518 460]
 [451 371 408 115]
 [956 316 537 527]]
Max a = 956
Row and Column is ([2],[0])
Min a = 115
Row and Column is ([1],[3])


In [73]:
### Read the csv file using genfromtxt
filename = "singapore-residents-by-ethnic-group-and-sex-end-june-annual.csv"
data = np.genfromtxt(filename, dtype=['i2', 'U50', 'i8'],
delimiter=',', names=True)
# print(data)
### Print out total rows of data in the file
print(f'There are altogether {len(data)} rows in the data file {filename}')
print()
### Print out the number of years of data captured
data_years = data['year']
years = np.unique(data_years)
print(f'There are {len(years)} years of data captured from {years[0]} to {years[-1]}')
## Extract only the rows with Total Residents" - using boolean indexing
keyword = 'Total Residents'
data_totalresidents = data[data['level_1'] == keyword]
# print(data_totalresidents)
### Print out the years which has the highest total number of residents
max_residents = data_totalresidents['value'].max()
argmax_residents = data_totalresidents['value'].argmax()
print(f'Year with the highest total number of residents: {data_totalresidents[argmax_residents]}')
print(f'Population Count: {max_residents} ')

### Print out the years which has the lowest total number of residents
min_residents = data_totalresidents['value'].min()
argmin_residents = data_totalresidents['value'].argmin()
print(f'Year with the lowest total number of residents: {data_totalresidents[argmin_residents]}')
print(f'Population Count: { min_residents } ')


There are altogether 855 rows in the data file singapore-residents-by-ethnic-group-and-sex-end-june-annual.csv

There are 57 years of data captured from 1960 to 2016
Year with the highest total number of residents: (2016, 'Total Residents', 3933559)
Population Count: 3933559 
Year with the lowest total number of residents: (1960, 'Total Residents', 1646400)
Population Count: 1646400 
